### PR TITLE
Updated dependencies and correction as per updates

### PR DESCRIPTION
**Pull request by MiyamotoAkira**
Python 3.6 is deprecated. I have set 3.11.5 just to put a version, but that could be changed. Also updated all dependencies and corrected issues raised by linting/mypy.

### CODE REVIEW

**Comment by MiyamotoAkira** [comment]
Hi,

we are currently using this project, and I wanted to add the ability to add ignore rules for lists and object list (same as #24 wanted). Right now I am using some bad hacks to do this.

But when trying to just install and run all tests, I found multiple issues.The changes in the PR are to correct those issues

**Comment by rugleb** [comment]
Hi! Thx for u contribution!
Globally, everything is fine, but the minimal version of python scares me.
The python 3.11 is too new, and many users may have a broken installation that is still sitting on 3.9-3.11.
I suggest to set`python=^3.9`.

**Comment by MiyamotoAkira** [comment]
Moved down to 3.9
Also py36-plus on add-trailing-comma no longer does anything
VERSION on the makefile doesn't seem to be used anywhere? Probably could be removed

**Comment by rugleb** [comment]
>  VERSION on the makefile doesn't seem to be used anywhere? Probably could be removed

yeah

**Comment by MiyamotoAkira** [comment]
Done

**Pull request merged**
